base_model: erickfmm/mrbert-es-sbert-ft
training:
  task: sbert
  gpu_temp_guard_enabled: false
  switch_on_thermal: false
  telemetry_log_interval: 1
  csv_log_path: "training_metrics_continual.csv"
  sbert:
    dataset_name: "erickfmm/agentlans__multilingual-sentences__paired_10_sts"
    dataset_type: paired_similarity
    columns:
      sentence1: sentence1
      sentence2: sentence2
      similarity: similarity
    output_dir: "./output/sbert_mrbert_continual"
    batch_size: 128
    gradient_accumulation_steps: 1
    max_grad_norm: 2.0
    epochs: 5
    warmup_steps: 100
    evaluation_steps: 5000
    checkpoint_save_steps: 1000
    resume_from_checkpoint: true
    learning_rate: 5.0e-6
    max_train_samples: null
    max_eval_samples: 20000
    max_seq_length: 512
    pooling_mode: mean
    use_amp: false
    resample_balanced: false
    resample_std: 0.3
    standardize_scores: true
    optimizer:
      optimizer_class: turbo_muon
      parameters:
        momentum: 0.95
        nesterov: true
        ns_steps: 4
        ns_eps: 1.0e-7
    wandb_project: "mrbert-es-sbert-continual-turbo-muon"
