base_model: BSC-LT/MrBERT-es
training:
  task: sbert
  sbert:
    dataset_name: "erickfmm/agentlans__multilingual-sentences__paired_10_sts"
    dataset_type: paired_similarity
    columns:
      sentence1: sentence1
      sentence2: sentence2
      similarity: similarity
    output_dir: "./output/sbert_modernbert"
    batch_size: 16
    epochs: 4
    warmup_steps: 1000
    evaluation_steps: 5000
    learning_rate: 2e-5
    max_train_samples: null
    max_eval_samples: 10000
    max_seq_length: 8192
    pooling_mode: mean
    use_amp: true
    resample_balanced: true
    resample_std: 0.3
